### PR TITLE
DEV-13080 enable JDBC random selection for Chiasm

### PR DESCRIPTION
**Pull request by mthyen**
@jleealpine @AndrewLngdn @midnighteuler Review? This is to enable random selection for various JDBC sources. I'll also have Kevin review when he returns.

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by mthyen** [comment]
Can someone review please? Code freeze is tonight. Thanks

**Comment by jleealpine** [comment]
Mike and I looked at this, we think it looks fine but in light of the news of Chiasm being pulled out of 5.7 and Mike wanting to revert a few changes he made himself, we might want to hold off on merging in this change for now.  We can maybe talk about this more tomorrow and see if this is something that should or shouldn't go in to 5.7.

**Comment by mthyen** [comment]
Okay, if Chiasm is pushed then the urgency on this drops. Plus I can work with Kevin on cleaning this up. Thanks.

**Pull request closed without merging**
