### PR TITLE
DEV-14625 / DEV-14689 workspace sidebar visual bugs

### PR DESCRIPTION
**Pull request by imccarter**
As noted in the Jira comments; I also took the opportunity to get rid of the "Activity" lozenge box that unnecessarily rendered on initial page load (DEV-14689). I'm not 100% satisfied with using jquery hide() and show(), but can't think of a better way without getting too crazy; open to suggestions.

### CODE REVIEW

**Comment by mmilano** [comment]
@imccarter 
if i read this correctly, it appears to call js to hide the content in the js on setup.

wouldnt it be better to have the tabs hidden by default in the tamplate & via css,
and then make sure they are visible when there is a selection?

**Comment by imccarter** [comment]
Yes, that is the case. I might be missing/forgetting something, but won't js have to get involved somewhere as to show or hide the content on (de)selection? Either via class assignment or like what I have here? 

Hiding them as a default via css and then un-hiding on selection (via js?) would probably be preferable and I can definitely do that. I'll play around, I could be overlooking some obvious fix...

**Comment by imccarter** [comment]
@mmilano 
Sorry for the delay. So the `$el.show()`s are still in there to have it display when a workspace is selected, but I've turned the `$el.hide()`s into `display: none` so it just initializes as hidden.

**Comment by imccarter** [comment]
Just noting that there's an issue for the 'Activity' box now; DEV-14689

**Pull request merged**
