### PR TITLE
Mark unsupported HDFS data sources as incomplete

### PR DESCRIPTION
**Pull request by AndrewLngdn**
@kevinmtrowbridge it would be good to get another pair of eyes on this

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by jleealpine** [comment]
Looks good, I'll merge

**Comment by jleealpine** [comment]
This needs to go into master as well, I presume?

**Comment by AndrewLngdn** [comment]
I can do it tomorrow

**Pull request merged**
