### PR TITLE
DEV-14658 hide grey list footer while loading

### PR DESCRIPTION
**Pull request by imccarter**
An admittedly somewhat hacky fix to get the list content footer to not show while the collection is being fetched. It would also inappropriately be visible while loading a list that wouldn't display it.

### CODE REVIEW

**Comment by imccarter** [comment]
Hold off on merging this, I'm going to change it so that it uses some class assignment rather than show to get the same effect. Still not the perfectly ideal fix, but a bit cleaner.

**Comment by imccarter** [comment]
As per Josh's recommendation I switched to using classes to hide then show the footer rather than using show(). I also made the listener for this a conditional `listenToOnce` for a bit cleaner implementation and changed the name of the option flag for clarity.

**Comment by mmilano** [comment]
@imccarter github tells me that this has conflicts and needs to be resolved.
however, is the problem still a problem? was this already merged? i havent been seeing the problem on pages...

**Comment by imccarter** [comment]
@mmilano I'm going to force push a fresh branch of these fixes here; merging master had some nasty conflicts that borked everything post-workspace list rework.

**Pull request closed without merging**
