### PR TITLE
Licensing chorus changes

### PR DESCRIPTION
**Pull request by jleealpine**

### CODE REVIEW

**Comment by jleealpine** [comment]
@midnighteuler or @kevinmtrowbridge can you guys take a look at these changes?  Essentially adding 4 new user types that each user can be assigned to.  Access to Alpine is now dependent on these user types ("Analytics Developer" and "Data Analyst" get access to Alpine, "Collaborator" and Business User" do not), also "Business User" user type only has access to Touchpoints (certain navigational elements like hamburger menu are disabled for this type of user and router.js will re-route to touchpoints catalog page if user tries to manually navigate to somewhere they are not supposed to).

Let me know if you have any questions about this, I'd be happy to talk about it tomorrow as well.

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by kevinmtrowbridge** [comment]
Thanks @jleealpine -- I am taking a look now.

**Comment by jleealpine** [comment]
@kevinmtrowbridge I merged these changes into master already, so I am closing the PR so that it can't be merged. Feel free to still use this to comment though if you have any thing you'd like to add to these changes.

**Pull request closed without merging**
