### PR TITLE
Changes when passing ENV vars to ruby subshells

### PR DESCRIPTION
**Pull request by kevin-alpine**
@midnighteuler: the mystery, slightly explained.

@kevinmtrowbridge will review more.

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by curran** [comment]
This would be great to merge in soon, as it fixes a useful script that is currently broken. I just tried installing Chorus on another dev machine and this error came up again. Posting the error here to have a record of it:

```
$ ./packaging/chorus_control.sh start
/Users/curran/repos/chorus/packaging/start-postgres.sh: line 22: /Users/curran/repos/chorus/postgres-db/pg_ctl.log: No such file or directory
[development] postgres failed to start, see /Users/curran/repos/chorus/postgres-db/server.log for details
[development] solr already running as process 10214.
[development] postgres must be running to start the indexer
[development] postgres must be running to start the worker
[development] postgres must be running to start the scheduler
[development] postgres must be running to start the web server
```

**Comment by kevin-alpine** [comment]
... as @curran stated, it's good to fix the `rake development:init` task -- with these changes it is working again.  I did search through the codebase for other places where ENV vars were being passed in that manner.  I found one other place and fixed it.  Merging in now.  Note this does not affect production, only developers.

**Comment by curran** [comment]
Woohoo!

**Pull request merged**
