### PR TITLE
DEV-13704 show data source credentials box when credentials are missing...

### PR DESCRIPTION
**Pull request by AndrewLngdn**
...when the user opens a workflow with an un-credentialed DS. Just needed to add a return statement so the page doesn't redirect with the dialog open. 

Also, show the name of the DS on the dialog so the user knows which credentials to enter

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by nkapinos** [comment]
@midnighteuler @kevin-alpine Can you review this ASAP?

**Comment by kevinmtrowbridge** [comment]
I am reviewing this now, @AndrewLngdn.  My apologies for the delay.

**Comment by kevinmtrowbridge** [comment]
Ok, thanks for your patience Andrew.  I pulled this code down in my dev machine.  I reproduced the bug which @mei-ling described here: https://alpine.atlassian.net/browse/DEV-13704 ... I checked-out this branch, I tried reproducing the bug again, and I could not.  I saw the new behavior that you described.

So, this LGTM!  Thanks for your work.

KT

**Comment by kevinmtrowbridge** [comment]
I am merging this branch so that we can verify and deliver it with tomorrow's build.

**Pull request merged**
