### PR TITLE
fix for de-humanizing table names in error message

### PR DESCRIPTION
**Pull request by atul-alpine**
@prakash-alpine @kevin-alpine I tested this on 204 but its not working. Need to check from where error and getting displayed and add the same code there. I tried it out but couldnt figure it out. Please check.

### CODE REVIEW

**Comment by kevin-alpine** [comment]
@atul-alpine: this issue is minor and it looks tricky.  I am making a call to push this one out.  Let's not worry about this for 5.6.

**Comment by prakash-alpine** [comment]
@kevin-alpine Can we review this? Why are you pushing it out?

**Comment by kevin-alpine** [comment]
It is a bug marked as minor, which was reported in March 2015, about an obscure string not being internationalized (when we only support english).  

Yesterday, we got an email from Lawrence stating: "... given we are working to stabilize the release, please don't commit any code other than that explicitly needed for 5.6."

Is this explicitly needed for 5.6?  It seems like a prime candidate for pushing out.

**Comment by prakash-alpine** [comment]
OK. No big deal. This can wait.

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by kevinmtrowbridge** [comment]
Closing old PRs.

**Pull request closed without merging**
