### PR TITLE
First pass at a text-area edit mode for HDFS connection parameters

### PR DESCRIPTION
**Pull request by midnighteuler**
I threw this together to help support out.

@mmilano could you have a look? It's functional, but not very pretty.

### CODE REVIEW

**Comment by jleealpine** [comment]
looks good, merge away

**Comment by mmilano** [comment]
please dont merge this in 6. defer until later.

**Comment by midnighteuler** [comment]
@jleealpine @mmilano Review/merge?

**Comment by jleealpine** [comment]
LGTM

**Pull request closed without merging**
