### PR TITLE
DEV-8655 Keep the activity list when quickstart is visible in workspace view

### PR DESCRIPTION
**Pull request by jmlewis**
Keep activity stream in workspace quick start view by adding it as a subview.

### CODE REVIEW

**Comment by jmlewis** [comment]
@prakash-alpine Not sure if assigning is the way that you track who's doing the code review. I figure you're the right person for my first few diffs :)

Also, rake jasmine:fixtures is failing for me — I may still need to update/add tests as part of this diff.

**Comment by jmlewis** [comment]
Have the specs running. Added a basic spec that checks for the presence of the subview container. Given that the subview itself is independently tested in its own spec is this sufficient?

If so I believe this is ready for review. I made the layout changes we discussed.

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by mmilano** [comment]
from discussions, we decided to hold on this for now and revise the sequencing of the page elements

**Pull request closed without merging**
