### PR TITLE
Increasing the default workfile size limit, to allow for larger model files.

### PR DESCRIPTION
**Pull request by jthompson6**
@jleealpine @kevin-alpine @midnighteuler @codedeft review?

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by codedeft** [comment]
I guess this works?

**Comment by kevin-alpine** [comment]
Hi Jenny,

Increasing this, increases the validation size applied to files attached via [paperclip](https://github.com/thoughtbot/paperclip) ... I don't see any reason why it wouldn't work.  It should be QAed though.

Reasons this might be bad:
* Maybe the HTTP connection will timeout before the 100mb file can be uploaded.  But, I don't think Chorus enforces a timeout.  Some platforms I have used like Heroku, do enforce a *25s timeout* ...
* This might cause the host system to run out of disk space sooner, if there are many 100mb attachments.

If it's necessary I suggest merging it in and QAing it thoroughly,
KT

**Comment by jthompson6** [comment]
@nkapinos can we merge?

**Comment by jthompson6** [comment]
LGTM

**Pull request merged**
