### PR TITLE
DEV-12995 prevent excessive roles in roles_users table

### PR DESCRIPTION
**Pull request by AndrewLngdn**
@midnighteuler @jleealpine 

'roles' was supposed to be an array but it was actually an Association

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can one of the admins verify this patch?

**Comment by nkapinos** [comment]
Can someone code review this ASAP?

**Comment by jleealpine** [comment]
looks good, feel free to merge this in

**Comment by kevinmtrowbridge** [comment]
Hi @AndrewLngdn, is this still something we want to merge in?  Let's either merge or close it.

**Comment by kevinmtrowbridge** [comment]
This is not necessary any more.  Cleaning up old PRs.

**Pull request closed without merging**
