### PR TITLE
Add description fields to jobs and workfiles

### PR DESCRIPTION
**Pull request by AndrewLngdn**
Last PR was messed up somehow so I cut a new one

@jleealpine I fixed the one comment you had so this should be good to go

### CODE REVIEW

**Comment by mmilano** [comment]
on working with, it becomes clear that the action 'rename workfile' is no longer appropriate. 
i'm closing this to rework the behavior and make it 'edit workfile details'

**Comment by AndrewLngdn** [comment]
@mmilano the PRs will update when you push changes to the branch, so we shouldn't need to close/re-open to get our changes in. I'm going to re-open this PR unless there was a different reason for closing

**Comment by mmilano** [comment]
@AndrewLngdn i closed it pretty much just because i am making changes, and didnt want anyone to accidentally merge it.

**Comment by mmilano** [comment]
@AndrewLngdn i found another feature gap: uploading a new file with text for the description doesnt appear to save the description text.

1. go to workfiles
2. action = upload file
3. pick a file.
4. add some description text.
5. submit
6. after success, edit details (ie, rename) of the file

**Comment by AndrewLngdn** [comment]
I'll check these problems out soon. Something strange must have happened because the behavior above worked when I was performing tests

**Comment by AndrewLngdn** [comment]
That issue should be fixed, it was a typo introduced by one of the later commits. Let me know if you see any other problems

**Comment by mmilano** [comment]
@AndrewLngdn could you please take a look at the branch-of-this-branch i made with UI and behavior changes & fixes?

https://github.com/Chorus/chorus/tree/add-description-mm

a number of changes:
* changing the 'rename' dialog over to 'edit details'
* changing the action labels
* refactoring some button labels to be more general-use in the app
* minor UI improvement to the new workflow dialog to make it more usable with the new description field
* cut out a pageevent & reload from workfile_show_page.js  because it appears to be redundant. :raised_hand: could you please verify that this is unnecessary?


**note**
:confounded: I did not adjust the test spec.js files to add checks for the description values, and request that you do so. I am not experienced in how to do that for a new field - do some other fixture files need to be changed too?

**Pull request merged**
