### PR TITLE
Fix for [DEV-12384]  For 5.6 release enable Touchpoints feature to be…

### PR DESCRIPTION
**Pull request by prakash-alpine**
DO NOT MERGE.

Fix for [DEV-12384]  For 5.6 release enable Touchpoints feature to be enabled/disabled via a configuration property

### CODE REVIEW

**Comment by prakash-alpine** [comment]
@mmilano @midnighteuler 
Please review this PR and let me know if this is sufficient to enable/disable Touchpoints for 5.6
Mike: verify that I have covered all code bases.
Michel:  Suggest UI treatment for disabled link for Touchpoints.

**Comment by mmilano** [comment]
i revised the styles to refactor the disabled out and update so that .disabled covers the primary bar.

**Comment by prakash-alpine** [comment]
@midnighteuler Please review and merge this PR.

**Comment by kevin-alpine** [comment]
Hi @prakash-alpine -- I pulled this down and ran it locally.  It works.

I made the disabled message a little tighter:
disabled

It probably makes sense to wait for @midnighteuler or @jleealpine to review.

**Pull request merged**
